


// const Sobre = () =>{
//     return(
//         <>
//         <h1>Sobre</h1>
//         <p>Dragon Ball Super (ドラゴンボール超スーパー Doragon Bōru Sūpā?) é uma série de anime criada por Akira Toriyama e produzida pela Toei Animation, que começou a ser exibida em 5 de julho de 2015 e teve seu ultimo episódio exibido em 25 de março de 2018 com um total de 131 episódios.[4][5][6] É também uma série de mangá escrita por Akira Toriyama e ilustrada por Toyotarō, serializada na revista de mangás shōnen V Jump da Shueisha. Dragon Ball Super é uma sequência para o mangá original Dragon Ball e a série de anime Dragon Ball Z, com o primeiro novo enredo em dezoito anos.[7][8]
// Dragon Ball Super segue as aventuras do protagonista Goku e seus amigos, depois de derrotar Majin Boo e trazer paz para Terra mais uma vez.[9][10] Goku encontra seres de longe mais poderosos e atinge o poder de um deus. Ele defende a Terra contra as poderosas divindades destrutivas e viaja para outros universos para encarar oponentes mais poderosos, assim como inimigos quase imparáveis, enquanto descobre seus novos poderes sob os deuses do universo.
// Em Portugal, a sua transmissão é feita pela Sociedade Independente de Comunicação (SIC)[11][12] (continuando a tradição iniciada com as séries anteriores), sendo um dos primeiros países a estrear a série. A dobragem ficou a cargo do estúdio Audio In, que manteve a grande maioria do elenco original (com a exceção de António Semedo, já falecido, e Fernanda Figueiredo, hoje reformada), adicionando também novas vozes. A transmissão teve início na manhã de 24 de setembro de 2016, sendo transmitidos novos episódios todos os sábados e domingos.[13] A SIC apenas transmitiu até ao episódio 104. A segunda parte, a partir do episódio 105, começou a ser transmitido pelo Biggs no 22 de julho de 2019 com algumas mudanças de 3 atores no elenco de dobragem.
// No Brasil, a série estreou legendada em outubro de 2016, na plataforma de fluxo de média Crunchyroll.[14] A dublagem do anime se iniciou em abril de 2017 no estúdio Unidub, onde a maior parte do elenco da dublagem original regressou.[15] O anime estreou dublado no país pelo Cartoon Network no dia 5 de agosto de 2017 e foi exibido de segunda a sexta às 15:30 da tarde e reprisando às 23:00 horas da noite e aos sábados com reprise dos 5 episódios às 23:00 da noite.[16] Em outubro de 2017, a emissora divulgou que o anime era a sua principal fonte de audiência.[17] Dragon Ball Super estreou na televisão aberta pela Band no programa Mais Geek em 16 de novembro de 2021 às 02:30.[18] Na Warner Channel o anime estreou no dia 3 de janeiro de 2022 às 08:43 substituindo Dragon Ball Z Kai.[19]
// Enred
// Ver artigo principal: Lista de personagens de Dragon Ball Super
// Ver também: Lista de episódios de Dragon Ball Super
// Saga Deus da Destruição:
// Ver também: Dragon Ball Z: Battle of Gods
// Algum tempo depois da derrota de Majin Boo, a paz finalmente regressou à Terra. Son Goku estabeleceu-se e, por exigência de Chi-Chi, trabalha agora como fazendeiro, para sustentar e apoiar a sua família. Sua família e amigos vivem agora vidas pacíficas.[20] No entanto, surge uma nova ameaça sob a forma de Bills, o Deus da Destruição, considerado a mais terrível e perigosa divindade no Universo 7. Após despertar de um longo sono de vários anos, Bills está ansioso para encontrar e lutar com um lendário guerreiro, que ele vira num sonho profético conhecido como o Deus Super Saiyajin (超スーパーサイヤ人ゴッド Sūpā Saiya-jin Goddo?).[21] Para proteger a Terra, Son Goku transforma-se no Deus Super Saiyajin para lutar com Bills. Apesar de perder, os seus esforços apaziguam o Deus da Destruição, de tal maneira que ele decide poupar o planeta. Esta parte da série, reconta os acontecimentos de Dragon Ball Z: Battle of Gods.
// Saga Freeza Dourado:
// Ver também: Dragon Ball Z: Fukkatsu no F
// Enquanto Son Goku e Vegeta partem com Bills e com o seu mestre e assistente Whis para treinar por um ano, dois remanescentes do exército de Freeza chegam à Terra e usam as Esferas do Dragão para o ressuscitar. Freeza reúne os seus exércitos e regressa para decretar a sua vingança sobŕe Son Goku e os seus amigos. Apesar de ficar forte o suficiente para alcançar uma nova transformação, ele é mais uma vez derrotado. Esta parte da série, reconta os acontecimentos de Dragon Ball Z: Resurrection 'F'.[22]
// Saga Sexto Universo:
// Em uma ocasião posterior, Champa, irmão gêmeo de Bills e o Deus da Destruição do Universo 6, convence Bills para lançar um torneio entre os melhores lutadores do universo de cada deus para a possessão da Terra. Goku e alguns de seus amigos se unem ao torneio, qual termina em uma surpreendente vitória para o time de Bills após os mais fortes lutadores de cada lado, Goku e Hit do Universo 6, acabarem perdendo. Na ocasião, Goku conhece e faz amizade com Zen-O, o rei de todos os universos. Goku promete arrumar um amigo para Zenō brincar.
// Saga Trunks do "Futuro
// Após o torneio ser completado, Trunks do Futuro reaparece e traz notícias de um novo e poderoso inimigo semelhante a Goku que é conhecido como Goku Black. Goku e os outros eventualmente descobrem que Goku Black é na verdade um Kaiō-shin do Universo 10 nomeado Zamasu, depois de assassinar Gowasu, pediu ao Super Shenlong das Super Esferas do Dragão para trocar de corpo com Goku de uma diferente linha de tempo, assassina Goku com o corpo de Zamasu, assassina Chi Chi e Goten, depois mata Gowasu do futuro, faz uma aliança com Zamasu do futuro e usa as Super Esferas do Dragão para se tornar imortal como parte de seu plano para alcançar a imortalidade e eliminar todos os mortais.[23] No fim, Zamasu é apagado junto com a linha de tempo do futuro inteira, por Zen-O do futuro, que acompanha Goku de volta para sua linha de tempo. Goku cumpre sua promessa para Zen-O por introduzir ele ao seu futuro eu.
// Saga da Sobrevivência do Universo:
// Algum tempo depois de Trunks do Futuro retornar para casa, Zen-O e o Zen-O do Futuro lançam um novo torneio chamado Torneio do Poder (力の大会 Chikara no Taikai?). O torneio multiverso apresenta times de lutadores de cada universo, como Goku sugeriu. Entretanto, isso se torna uma batalha pela sobrevivência quando ambos Zenō declaram que os universos derrotados no torneio irão ser apagados.[24] Goku, Vegeta, Gohan, Piccolo, Kuririn, Mestre Kame, Tenshinhan, Androide 18, Androide 17 e um temporariamente revivido Freeza se unem ao torneio como representantes do Universo 7 para protegê-lo. Apesar do fato que Zen-O do Presente e Zen-O do Futuro já tinham a intenção de destruir os universos mais fracos, a maioria dos lutadores dos outros universos que estavam desconhecidos disso veem Goku como um vilão por sugerir lançar o torneio em primeiro lugar. Fora dos doze universos, apenas quatro (universo 1, 5, 8, e 12) são isentos de participarem devido a que seus habitantes terem uma média mortal de classificação acima de 7. Goku alcança uma nova forma de deus conhecida como o Instinto Superior (身勝手の極意 Migatte no Gokui?), qual aumenta sua agilidade e poder e permite que ele se mova automaticamente sem seu cérebro precisar mandar sinais para seu corpo.[25] O torneio termina com Goku e Freeza derrubando Jiren junto com eles mesmos. Isso deixa o Androide 17 como o único competidor remanescente e o vencedor do Torneio de Poder. Como recompensa, Androide 17 recebe um desejo das Super Esferas do Dragão. O Grande Sacerdote convoca o Super Shenlong das Super Esferas do Dragão, o qual diz para Super Shenlong na linguagem dos deuses o desejo do Androide 17 de restaurar todos os universos apagados. Por seus esforços no torneio, Freeza é totalmente revivido e se reúne ao seu exército. Goku e seus amigos voltam para suas vidas diárias na Terra.
// Saga Broly
// Ver artigo principal: Dragon Ball Super: Broly
// A história passa anos a frente em que Chirai e Remo resgatam Broly e Paragus do inóspito planeta Vampa. Eles vão até o QG de Freeza e Paragus apresenta o controle remoto capaz de eletrificar Broly. Broly por sua vez possui um bom temperamento, diferente do filme em que possui um comportamento insano e descontrolado. Logo na Terra, Goku treina para ficar mais forte e Vegeta para superar Freeza que foi revivido por Whis. Trunks notifica que o exército de Freeza roubou as Esferas do Dragão. Tanto Bulma quanto Freeza tinham desejos bobos, um redução na idade e Freeza com relação a sua estatura. Ambos os dois lados se reúnem e Vegeta enfrenta Broly usando o Super Saiyajin e o Broly sua forma base, mas Broly libera um poder que as pupilas de seus olhos mudam de cor. Paragus tenta parar Broly, mas percebe que o controle não está com ele porque Chirai o destruiu. Vegeta assume a forma de Super Saiyajin God, mas não equivale na luta contra Broly até chegar a vez de Goku e enfrentar Broly até chegar ao estágio God. Goku percebe que Broly não é mau, mas nada detém os movimentos dele até deixar Goku impossibilitado. Piccolo contata Goku e diz que mesmo Piccolo indo ao campo de batalha não seria de grande ajuda e Goku fala se tudo não sair tudo conforme, usaria o teletransporte. Goku já vai para o Blue e supera Broly e Freeza mata Paragus, fazendo Broly passar pela mesma experiência que Goku passou ao matar Kuririn pela segunda vez se tornando o Super Sayajin Berseker. Goku e Vegeta lutam contra Broly na forma Blue, mas o curso da luta não muda e levam Broly em direção ao Freeza que então Broly o espanca, até mesmo na forma Golden Freeza. Goku pega Vegeta e usa o teletransporte para onde está Piccolo. Goku pede a Senzu, mas Piccolo não possui e Goku recorre a fusão. Duas fusões imperfeitas, de um velho e um gorducho, na terceira vez forma o Gogeta. Gogeta enfrenta Broly salvando Freeza. Mesmo Broly enfrentando Gogeta, Chirai percebe que Broly é gentil e só luta por causa das ações de Paragus. Chirai usa as Esferas do Dragão e usa seu desejo para mandar Broly para o planeta Vampa. Chirai e Remo vão atrás de Broly. Freeza tenta destruí-los, mas Gogeta não deixa e Freeza jura retornar. Goku vai ao planeta Vampa em que faz amizade com Chirai, Remo e Broly e depois se despede dizendo que como se chamava, na Terra como Son Goku e na língua Saiyajin Kakaroto.
// Saga Patrulha Galáctica:
// Logo depois do torneio, Goku e Vegeta treinam na máquina de gravidade, mas Bulma notifica que Boo está sendo sequestrado. Ao chegarem na residência do Mr. Satan, nota-se que é a Patrulha Galáctica que está tentando sequestrar Boo. Goku e Vegeta são colocados inconscientes facilmente por uma arma de raio e levados para o QG da Patrulha Galáctica. Lá eles reveem Jaco e lá conhecem Mills, que conta um pouco sua história do Dai Kaiō-shin (Sagrado Sr. Kaiō) e do Kaiō-shin do Sul antes de serem absorvidos por Boo e quando eles enfrentam Moro tempo atrás. Como Boo estava dormindo e não podia acordar, Goku e Vegeta ingressam na Patrulha Galáctica e a ameaça de Moro se estendia no planeta Namekusei.
// Produçã
// Dragon Ball Super foi anunciado pela Toei Animation em 28 de abril de 2015[26] na cidade de Shinjuku, dez dias após a estreia do filme Dragon Ball Z: Fukkatsu no F.[27][28][29] É a primeira série de anime da franquia Dragon Ball produzida dezoito anos após Dragon Ball GT, que foi exibida entre 1996 e 1997. Não tendo relação com DBGT, a história mostra eventos colocados antes do final do mangá original (capítulos 518 e 519) e do anime Dragon Ball Z (episódios 289, 290 e 291).
// Além de seu papel como criador da série, Akira Toriyama, é também creditado pela "história original e conceitos de design de personagem" do novo anime originalmente dirigido por Kimitoshi Chioka. Toriyama elaborou em seu envolvimento com a "saga Trunks do Futuro" dizendo que ele criou a história baseada em sugestões do departamento editorial, "Como com a última vez, eu escrevi a linha de tempo do enredo geral, e os roteiristas têm estado compilando e expandido o conteúdo da história para episódios individuais, fazendo várias mudanças e adições, e geralmente fazendo seu melhor para fazer a história mais interessante."[30] Em adição para novos personagens desenhados por Toriyama, outros personagens para a "saga Sobrevivência do Universo" foram desenhados por Toyotarō, artista da adaptação de mangá do anime, e um pouco por ambos.[31]
// O produtor da Toei Animation, Atsushi Kido, previamente trabalhou em Dragon Ball Z por um curto tempo durante a saga Freeza, enquanto o produtor da Fuji TV, Osamu Nozaki, diz que ele tem sido um fã da série desde a infância.[32] Morio Hatano, diretor da série de Saint Seiya Omega (episódios #1–51), começou a compartilhar o crédito de diretor da série com Chioka começando com o episódio #33, antes de tomar isso adiante completamente com o #47. Do episódio #68 para #76, Morio Hatano compartilhou o papel de diretor da série com Kōhei Hatano (sem relação), outro artista de storyboards e diretor de episódio para a série.
// Masako Nozawa reprisa seus papéis como Son Goku, Son Gohan, e Son Goten. A maioria do elenco original bem como reprisa seus papéis.[23][33] Entretanto, os papéis de Jōji Yanami como Kaiō-sama e o narrador foram indefinidamente tomados por Naoki Tatsuta a partir do episódio 12, para que Yanami pudesse tomar saída médica.[34] Kōichi Yamadera e Masakazu Morita também retornaram como Bills e Whis, respectivamente.[33]
// A primeira prévia da série foi exibida em 14 de junho de 2015, seguindo o episódio 157 de Dragon Ball Z Kai.[35] No dia seguinte, a principal imagem promocional para Dragon Ball Super foi adicionada ao seu website oficial e revelou dois novos personagens,[33] que foram mais tarde revelados para serem nomeados Champa e Vados, respectivamente.[36] Um trailer de trinta segundos incluindo os novos personagens foi baixado para o website oficial da série em 26 de junho de 2015.[37]
// Transmissão e produção internacion
// Dragon Ball Super recebeu uma dublagem em inglês que estreou no canal Toonami no Sudeste Asiático e Índia em 21 de janeiro de 2017. Essa dublagem é produzida pela Bang Zoom! Entertainment localizada em Los Angeles para o mercado asiático. Um sneak preview da dublagem em inglês foi exibida em 17 de dezembro de 2016, e apresentou o primeiro episódio.[38] Sean Schemmel dublou Goku, Goku Black e King Kai.
// Começando em 2016, a série tem sido exibida em Israel na Nickelodeon e em Portugal na SIC.[39
// Em 10 de outubro de 2016, Toei Animation Europe anunciou que Dragon Ball Super iria ser transmitido na França, Itália, Espanha, e na África de língua inglesa no final de 2016.[40] Mais tarde naquele mesmo mês, Toei Animation anunciou um sub oficial em inglês da série que seria simultaneamente exibida legalmente na Crunchyroll, Daisuki.net, e Anime Lab começando em 22 de outubro de 2016.[41][42]
// Em 4 de outubro de 2016, Funimation anunciou que a companhia adquiriu os direitos para Dragon Ball Super e que iria ser produzida uma dublagem em inglês, com muitos membros do elenco de seus anteriores lançamentos em língua inglesa da mídia Dragon Ball reprisando seus respectivos papéis. Bem como oficialmente anunciando a dublagem, foi também anunciado que eles iriam simultaneamente transmitir a série em sua plataforma de streaming, FunimationNow.[43][44] Em 7 de dezembro de 2016, IGN reportou que a dublagem em inglês da Funimation de Dragon Ball Super iria ao ar no Adult Swim aos sábados às 20h com um encore exibido em seu bloco Toonami mais tarde naquela noite às 23h30 começando em 7 de janeiro de 2017.[45] Isso foi mais tarde confirmado na página oficial do Toonami no Facebook.[46] A estreia na América do Norte de Dragon Ball Super foi assistida por 1,063,000 de espectadores para seu horário das 20h exibida no Adult Swim.[47]
// No Brasil, a série estreou em outubro de 2016 no serviço de fluxo de média simulcast Crunchyroll,[14] em junho de 2017, foi anunciado que o estúdio Unidub, que tem Wendel Bezerra (dublador de Son Goku desde 1999)[48] como um dos fundadores,[49] estava dublando a série, que seria lançada no Cartoon Network em 5 de agosto do mesmo ano.[50] Em outubro do mesmo ano, a emissora revelou que a programação com a maior audiência no canal.[17] Ainda no mesmo mês, Cartoon Network anunciou o fim da exibição inédita no dia 7 de novembro de 2017 a partir do episódio 67 e início das reprises no dia 8 do mesmo mês. Em 1 de outubro de 2018, voltou a ter novos episodios no Brasil.
// Mús
// Norihito Sumitomo, o compositor para Battle of Gods e Resurrection 'F continua em Dragon Ball Super.[51] Uma trilha sonora original para o anime foi lançada em CD pela Nippon Columbia em 24 de fevereiro de 2016.[52
// A canção do primeiro tema de abertura para episódios 1 a 76 é "Chōzetsu☆Dynamic!" (超絶☆ダイナミック！ Chōzetsu Dainamikku?, "Excellent Dynamic!") por Kazuya Yoshii de The Yellow Monkey e a versão brasileira por Daniel Quirino. A letra foi escrita por Yukinojo Mori que tinha escrito numerosas canções para a série Dragon Ball.[53] A canção do segundo tema de abertura do episódio 77 em diante é "Genkai Toppa × Survivor" (限界突破×サバイバー? "Limit Break × Survivor") pelo cantor Kiyoshi Hikawa e a versão brasileira por Rodrigo Rossi. Yukinojo Mori escreveu a letra para a canção de rock e Takafumi Iwasabi compôs a música.[54][55]
// A canção do primeiro tema de encerramento para episódios 1 a 12 é "Hello Hello Hello" (ハローハローハロー Harō Harō Harō?) pela banda de rock japonesa Good Morning America e a versão brasileira por Rodrigo Rossi.[53] A canção do segundo tema de encerramento para episódios 13 a 25 é "Starring Star" (スターリングスター Sutāringu Sutā?) pelo grupo Key Talk e a versão brasileira por Ricardo Fábio.[56] O cantor para a dublagem em inglês da Funimation é Professor Shyguy.[57] A canção do terceiro encerramento para episódios 26 a 36 é "Usubeni" (薄紅? "Light Pink") pela banda Lacco Tower e a versão brasileira por Bruno Sutter. A canção do quarto tema de encerramento para episódios 37 a 49 é "Forever Dreaming" por Czecho No Republic e a versão brasileira por Roger Ciel.[58] A canção do quinto tema de encerramento para episódios 50 a 59 é "Yokayoka Dance" (よかよかダンス Yokayoka Dansu?, "It's Fine Dance") pelo idol group Batten Showjo Tai e a versão brasileira por Gabi Milani.[59] O sexto tema de encerramento para episódios 60 a 72 é "Chao Han Music" (炒飯MUSIC Chāhan Myūjikku?) por Arukara e a versão brasileira por Ricardo Cruz.[60] O sétimo tema de encerramento é dos episódios 73 a 83 é "Aku no Tenshi to Seigi no Akuma" (悪の天使と正義の悪魔? "Evil Angel and Righteous Devil") por The Collectors e a versão brasileira por Alex Ci.[61] O oitavo tema de encerramento dos episódios 84 a 96 é "Boogie Back" por Miyu Inoue e a versão brasileira por Deborah Moreira.[62][63] O nono tema de encerramento dos episódios 97 a 108 é "Haruka" (遥?) por Lacco Tower e a versão brasileira por Ricardo Cruz.[64] O décimo tema de encerramento dos episódios 109 até 121 é "70cm Shiho no Madobe" (70cm四方の窓辺? "By a 70cm Square Window") por RottenGraffty e a versão brasileira por Raphael Rossatto.[65] Dos episódios 122 até 131, o décimo-primeiro tema de encerramento é "Lagrima" por OnePixcel. e a versão brasileira por Mary Minoboli[66] O tema de inserção do tema Instinto Superior é cantado por Akira Kushida e a versão brasileira por Bruno Sutter.</p>
//         </>
//     )
// }

// export default Sobre;